### ISSUE TITLE
how to get vgg.16 features of image ?

### ISSUE THREAD

**Issue by jjqcat** [Photogrammetry-Robotics-Bonn/vpr_relocalization#1]
Hi, nice project! I'm interested in it and ready to test with my own database, but how to get vgg.16 features  of image? is there any tool ?

Best regards
jjqcat

**Comment by jjqcat** [comment]
or OverFeat features?

**Comment by ovysotska** [comment]
Hi @jjqcat ,

sorry for the late reply. We don't provide any tool for extracting the features. Our assumption is that the features are already stored in individual text files.
But the following pages, provide tutorials how to extract the [OverFeat](https://github.com/sermanet/OverFeat) and [VGG-16] (https://keras.io/applications/) features.

Hope this helps!
