### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by BIT-MJY** [Photogrammetry-Robotics-Bonn/vpr_relocalization#3]
Hello authors,

Thanks for sharing your work!

I have met an error in the compile process:

```
CMake Error at googletest-download/googletest-download-prefix/tmp/googletest-download-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'
```
solved by setting the `git tag` in `gtest/CMakeLists.txt` to "main" instead of "master".

This may be caused by the update of google-test, and thus the default `git tag` in `gtest/CMakeLists.txt`  is suggested to be changed :)

**Comment by ovysotska** [comment]
Great, thanks for finding that out :)
In case you run into more issues please consider a newer version of the code https://github.com/ovysotska/image_sequence_localizer
